# Generated by Django 3.2.9 on 2021-11-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NFT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('token', models.IntegerField()),
                ('img', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=200)),
            ],
        ),
    ]
